title: Julia Popko
email: 
description: 
baseurl: "/"
url: "https://julia-popko.github.io"
github_username: 

markdown: kramdown

collections:
  projects:
    output: true

sass:
    style: compressed
    sass_dir: _sass
