title: Julia Popko
email: contact@julia-popko.design
description: Portfolio of Julia Popko, UX / UI Designer based in Warsaw
baseurl: "/"
url: "https://www.julia-popko.design"
author: Julia Popko
year: 2020
footer: Hand-crafted by Julia
type: designer_portfolio
lang: en
cover_og: porfolio-ogi.png
favicon: portfolio-favicon.png
cv_pl: 2020-cv-pl.pdf
cv_en: 2020-cv-eng.pdf
keywords:
  - Designer
  - Portfolio
  - UX Design
  - UI Design
  - Warsaw

markdown: kramdown

collections:
  projects:
    output: true
    permalink: /:title/

sass:
    style: compressed
    sass_dir: _sass

permalink: /:title/

defaults:
  -
    scope:
      type: projects
    values:
      layout: projects
  -
    scope:
      path: ""
    values:
      layout: "default"