title: Julia Popko
email: juliettapop@gmail.com
description: Portfolio of Julia Popko, UX / UI Designer
baseurl: "/"
url: "https://julia-popko.github.io"

markdown: kramdown

collections:
  projects:
    output: true

sass:
    style: compressed
    sass_dir: _sass
