backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"

public_folder: "static/uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "index"
        file: "/index.md"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "home" }
          - { label: "Title", name: "title", widget: "string" }
